<?php  
//Central California City Names

$central_california = array(
	"Acton",
	"Ahwahnee",
	"Armona",
	"Arvin",
	"Atwater",
	"Auberry",
	"Avenal",
	"Badger",
	"Bakersfield",
	"Ballico",
	"Bass lake",
	"Benton",
	"Big pine",
	"Bishop",
	"Bodfish",
	"Boron",
	"Buttonwillow",
	"Caliente",
	"California city",
	"Caruthers",
	"Ceres",
	"Chowchilla",
	"Clovis",
	"Coalinga",
	"Coarsegold",
	"Columbia",
	"Corcoran",
	"Coulterville",
	"Crows landing",
	"Cutler",
	"Del rey",
	"Delano",
	"Delhi",
	"Denair",
	"Dinuba",
	"Dos palos",
	"Dunlap",
	"Earlimart",
	"Edwards",
	"El nido",
	"Escalon",
	"Exeter",
	"Farmersville",
	"Fellows",
	"Firebaugh",
	"Fowler",
	"Frazier park",
	"Fresno",
	"Friant",
	"Glennville",
	"Groveland",
	"Gustine",
	"Hanford",
	"Hickman",
	"Hilmar",
	"Hollister",
	"Hughson",
	"Hume",
	"Independence",
	"Inyokern",
	"Ivanhoe",
	"Jamestown",
	"June lake",
	"Keene",
	"Kerman",
	"Kernville",
	"Keyes",
	"Kingsburg",
	"La grange",
	"Lake hughes",
	"Lake isabella",
	"Lamont",
	"Lancaster",
	"Lathrop",
	"Laton",
	"Legrand",
	"Lemoore",
	"Lindsay",
	"Littlerock",
	"Livingston",
	"Llano",
	"Lodi",
	"Lompoc",
	"Lone pine",
	"Long barn",
	"Los banos",
	"Lost hills",
	"Madera",
	"Mammoth lakes",
	"Manteca",
	"Maricopa",
	"Mariposa",
	"Mcfarland",
	"Mendota",
	"Merced",
	"Miramonte",
	"Mi-wuk village",
	"Modesto",
	"Mojave",
	"Monterey",
	"Newman",
	"North fork",
	"Oakdale",
	"Oakhurst",
	"Onyx",
	"Orange cove",
	"Orosi",
	"Palmdale",
	"Parlier",
	"Patterson",
	"Pearblossom",
	"Pismo beach",
	"Pixley",
	"Planada",
	"Porterville",
	"Posey",
	"Prather",
	"Raisin city",
	"Raymond",
	"Reedley",
	"Ridgecrest",
	"Ripon",
	"Riverbank",
	"Riverdale",
	"Rosamond",
	"Salida",
	"Salinas",
	"San joaquin",
	"San luis obispo",
	"Sanger",
	"Santa maria",
	"Selma",
	"Shafter",
	"Shaver lake",
	"Snelling",
	"Sonora",
	"Soulsbyville",
	"Springville",
	"Squaw valley",
	"Stevinson",
	"Stockton",
	"Stratford",
	"Strathmore",
	"Taft",
	"Tehachapi",
	"Terra bella",
	"Three rivers",
	"Tipton",
	"Tollhouse",
	"Tracy",
	"Tranquillity",
	"Trona",
	"Tulare",
	"Tuolumne",
	"Turlock",
	"Twain harte",
	"Valyermo",
	"Vernalis",
	"Visalia",
	"Wasco",
	"Waterford",
	"Watsonville",
	"Weldon",
	"Winton",
	"Wishon",
	"Wofford heights",
	"Woodlake",
);
?>

<div class="p-5 m-5">
	<h2 class="text-center pb-5">Central California Locations</h2>
	<ul class="list-of-cities">
		<?php foreach($central_california as $city) : ?>
			<li><a href="/california-<?php echo strtolower(str_replace(" ", "-", $city)); ?>-solar-installation/"
				title="<?php echo $city ?> Solar Installation"><?php echo $city ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>