<?php $new_jersey_cities = array(
    "Absecon",
    "Allamuchy-Panther Valley",
    "Allendale",
    "Allenhurst",
    "Allentown",
    "Allenwood",
    "Alloway",
    "Alpha",
    "Alpine",
    "Andover",
    "Annandale",
    "Asbury Park",
    "Ashland",
    "Atlantic City",
    "Atlantic Highlands",
    "Audubon",
    "Audubon Park",
    "Avalon",
    "Avenel",
    "Avon-by-the-Sea",
    "Barclay-Kingston",
    "Barnegat",
    "Barnegat Light",
    "Barrington",
    "Bay Head",
    "Bayonne",
    "Beach Haven",
    "Beach Haven West",
    "Beachwood",
    "Beatyestown",
    "Beckett",
    "Belford",
    "Belleville",
    "Bellmawr",
    "Belmar",
    "Belvidere",
    "Bergenfield",
    "Berkeley Heights",
    "Berlin",
    "Bernardsville",
    "Beverly",
    "Blackwood",
    "Bloomfield",
    "Bloomingdale",
    "Bloomsbury",
    "Bogota",
    "Boonton",
    "Bordentown",
    "Bound Brook",
    "Bradley Beach",
    "Branchville",
    "Brass Castle",
    "Bridgeton",
    "Brielle",
    "Brigantine",
    "Brooklawn",
    "Browns Mills",
    "Brownville",
    "Budd Lake",
    "Buena",
    "Burlington",
    "Butler",
    "Caldwell",
    "Califon",
    "Camden",
    "Cape May",
    "Cape May Court House",
    "Cape May Point",
    "Carlstadt",
    "Carneys Point",
    "Carteret",
    "Cedar Glen Lakes",
    "Cedar Glen West",
    "Cedar Grove",
    "Cedarville",
    "Chatham",
    "Cherry Hill Mall",
    "Chesilhurst",
    "Chester",
    "Clark",
    "Clayton",
    "Clearbrook Park",
    "Clementon",
    "Cliffside Park",
    "Cliffwood Beach",
    "Clifton",
    "Clinton",
    "Closter",
    "Collings Lakes",
    "Collingswood",
    "Colonia",
    "Concordia",
    "Corbin City",
    "Country Lake Estates",
    "Cranbury",
    "Crandon Lakes",
    "Cranford",
    "Cresskill",
    "Crestwood Village",
    "Dayton",
    "Deal",
    "Demarest",
    "Diamond Beach",
    "Dover",
    "Dover Beaches North",
    "Dover Beaches South",
    "Dumont",
    "Dunellen",
    "East Brunswick",
    "East Freehold",
    "East Newark",
    "East Orange",
    "East Rutherford",
    "Eatontown",
    "Echelon",
    "Edgewater",
    "Edison",
    "Egg Harbor City",
    "Elizabeth",
    "Elmer",
    "Elmwood Park",
    "Elwood-Magnolia",
    "Emerson",
    "Englewood",
    "Englewood Cliffs",
    "Englishtown",
    "Erlton-Ellisburg",
    "Erma",
    "Essex Fells",
    "Estell Manor",
    "Ewing",
    "Fairfield",
    "Fair Haven",
    "Fair Lawn",
    "Fairton",
    "Fairview",
    "Fairview",
    "Fanwood",
    "Far Hills",
    "Farmingdale",
    "Fieldsboro",
    "Flemington",
    "Florence-Roebling",
    "Florham Park",
    "Folsom",
    "Fords",
    "Forked River",
    "Fort Dix",
    "Fort Lee",
    "Franklin",
    "Franklin Lakes",
    "Freehold",
    "Frenchtown",
    "Garfield",
    "Garwood",
    "Gibbsboro",
    "Gibbstown",
    "Glassboro",
    "Glendora",
    "Glen Gardner",
    "Glen Ridge",
    "Glen Rock",
    "Gloucester City",
    "Golden Triangle",
    "Great Meadows-Vienna",
    "Greentree",
    "Guttenberg",
    "Hackensack",
    "Hackettstown",
    "Haddonfield",
    "Haddon Heights",
    "Haledon",
    "Hamburg",
    "Hammonton",
    "Hampton",
    "Harrington Park",
    "Harrison",
    "Harvey Cedars",
    "Hasbrouck Heights",
    "Haworth",
    "Hawthorne",
    "Heathcote",
    "Helmetta",
    "High Bridge",
    "Highland Lake",
    "Highland Park",
    "Highlands",
    "Hightstown",
    "Hillsdale",
    "Hillside",
    "Hi-Nella",
    "Hoboken",
    "Ho-Ho-Kus",
    "Holiday City-Berkeley",
    "Holiday City South",
    "Holiday Heights",
    "Hopatcong",
    "Hopewell",
    "Interlaken",
    "Irvington",
    "Iselin",
    "Island Heights",
    "Jamesburg",
    "Jersey City",
    "Keansburg",
    "Kearny",
    "Kendall Park",
    "Kenilworth",
    "Keyport",
    "Kingston",
    "Kinnelon",
    "Lakehurst",
    "Lake Mohawk",
    "Lake Telemark",
    "Lakewood",
    "Lambertville",
    "Laurel Lake",
    "Laurel Springs",
    "Laurence Harbor",
    "Lavallette",
    "Lawnside",
    "Lawrenceville",
    "Lebanon",
    "Leisure Knoll",
    "Leisuretowne",
    "Leisure Village",
    "Leisure Village East",
    "Leisure Village West-Pine Lake Park",
    "Leonardo",
    "Leonia",
    "Lincoln Park",
    "Lincroft",
    "Linden",
    "Lindenwold",
    "Linwood",
    "Little Falls",
    "Little Ferry",
    "Little Silver",
    "Livingston",
    "Loch Arbour village",
    "Lodi",
    "Long Branch",
    "Longport",
    "Long Valley",
    "Lyndhurst",
    "McGuire AFB",
    "Madison",
    "Madison Park",
    "Magnolia",
    "Manahawkin",
    "Manasquan",
    "Mantoloking",
    "Manville",
    "Maplewood",
    "Margate City",
    "Marlton",
    "Matawan",
    "Mays Landing",
    "Maywood",
    "Medford Lakes",
    "Mendham",
    "Mercerville-Hamilton Square",
    "Merchantville",
    "Metuchen",
    "Middlesex",
    "Midland Park",
    "Milford",
    "Millburn",
    "Millstone",
    "Milltown",
    "Millville",
    "Monmouth Beach",
    "Monmouth Junction",
    "Montclair",
    "Montvale",
    "Moonachie",
    "Moorestown-Lenola",
    "Morganville",
    "Morris Plains",
    "Morristown",
    "Mountain Lakes",
    "Mountainside",
    "Mount Arlington",
    "Mount Ephraim",
    "Mullica Hill",
    "Mystic Island",
    "National Park",
    "Navesink",
    "Neptune City",
    "Netcong",
    "Newark",
    "New Brunswick",
    "New Egypt",
    "Newfield",
    "New Milford",
    "New Providence",
    "Newton",
    "North Arlington",
    "North Beach Haven",
    "North Brunswick Township",
    "North Caldwell",
    "North Cape May",
    "Northfield",
    "North Haledon",
    "North Middletown",
    "North Plainfield",
    "Northvale",
    "North Wildwood",
    "Norwood",
    "Nutley",
    "Oakhurst",
    "Oakland",
    "Oaklyn",
    "Oak Valley",
    "Ocean Acres",
    "Ocean City",
    "Ocean Gate",
    "Ocean Grove",
    "Oceanport",
    "Ogdensburg",
    "Old Bridge",
    "Old Tappan",
    "Olivet",
    "Oradell",
    "Orange",
    "Oxford",
    "Palisades Park",
    "Palmyra",
    "Paramus",
    "Park Ridge",
    "Passaic",
    "Paterson",
    "Paulsboro",
    "Peapack and Gladstone",
    "Pemberton",
    "Pemberton Heights",
    "Pennington",
    "Pennsauken",
    "Penns Grove",
    "Pennsville",
    "Perth Amboy",
    "Phillipsburg",
    "Pine Beach",
    "Pine Hill",
    "Pine Ridge at Crestwood",
    "Pine Valley",
    "Pitman",
    "Plainfield",
    "Plainsboro Center",
    "Pleasantville",
    "Point Pleasant",
    "Point Pleasant Beach",
    "Pomona",
    "Pompton Lakes",
    "Port Monmouth",
    "Port Norris",
    "Port Reading",
    "Port Republic",
    "Presidential Lakes Estates",
    "Princeton",
    "Princeton Junction",
    "Princeton Meadows",
    "Princeton North",
    "Prospect Park",
    "Rahway",
    "Ramblewood",
    "Ramsey",
    "Ramtown",
    "Raritan",
    "Red Bank",
    "Ridgefield",
    "Ridgefield Park village",
    "Ridgewood village",
    "Ringwood",
    "Rio Grande",
    "Riverdale",
    "River Edge",
    "Riverton",
    "River Vale",
    "Rochelle Park",
    "Rockaway",
    "Rockleigh",
    "Rocky Hill",
    "Roosevelt",
    "Roseland",
    "Roselle",
    "Roselle Park",
    "Rosenhayn",
    "Rossmoor",
    "Rumson",
    "Runnemede",
    "Rutherford",
    "Saddle Brook",
    "Saddle River",
    "Salem",
    "Sayreville",
    "Scotch Plains",
    "Sea Bright",
    "Seabrook Farms",
    "Sea Girt",
    "Sea Isle City",
    "Seaside Heights",
    "Seaside Park",
    "Secaucus",
    "Sewaren",
    "Shark River Hills",
    "Shiloh",
    "Ship Bottom",
    "Shrewsbury",
    "Silver Ridge",
    "Society Hill",
    "Somerdale",
    "Somerset",
    "Somers Point",
    "Somerville",
    "South Amboy",
    "South Belmar",
    "South Bound Brook",
    "South Orange",
    "South Plainfield",
    "South River",
    "South Toms River",
    "Spotswood",
    "Springdale",
    "Springfield",
    "Spring Lake",
    "Spring Lake Heights",
    "Stanhope",
    "Stockton",
    "Stone Harbor",
    "Stratford",
    "Strathmere",
    "Strathmore",
    "Succasunna-Kenvil",
    "Summit",
    "Surf City",
    "Sussex",
    "Swedesboro",
    "Tavistock",
    "Teaneck",
    "Tenafly",
    "Teterboro",
    "Tinton Falls",
    "Toms River",
    "Totowa",
    "Trenton",
    "Tuckerton",
    "Turnersville",
    "Twin Rivers",
    "Union",
    "Union Beach",
    "Union City",
    "Upper Saddle River",
    "Ventnor City",
    "Vernon Valley",
    "Verona",
    "Victory Gardens",
    "Victory Lakes",
    "Villas",
    "Vineland",
    "Vista Center",
    "Waldwick",
    "Wallington",
    "Wanamassa",
    "Wanaque",
    "Waretown",
    "Washington",
    "Washington Township",
    "Watchung",
    "Wayne",
    "Wenonah",
    "West Belmar",
    "West Caldwell",
    "West Cape May",
    "Westfield",
    "West Freehold",
    "West Long Branch",
    "West Milford",
    "West New York",
    "West Orange",
    "West Paterson",
    "Westville",
    "West Wildwood",
    "Westwood",
    "Wharton",
    "White Horse",
    "White House Station",
    "White Meadow Lake",
    "Whitesboro-Burleigh",
    "Whittingham",
    "Wildwood",
    "Wildwood Crest",
    "Williamstown",
    "Woodbine",
    "Woodbridge",
    "Woodbury",
    "Woodbury Heights",
    "Woodcliff Lake",
    "Woodlynne",
    "Wood-Ridge",
    "Woodstown",
    "Wrightstown",
    "Wyckoff",
    "Yardville-Groveville",
    "Yorketown",
); ?>

<div class="p-5 m-5">
    <h2 class="text-center pb-5">New Jersey Locations</h2>
    <ul class="list-of-cities">
        <?php foreach ($new_jersey_cities as $city) : ?>

            <!-- <li><?php //echo $city ?></li> -->
            <li><a href="/new-jersey-<?php echo strtolower(str_replace(" ", "-", $city)); ?>-solar-installation/"
                title="<?php echo $city ?> Solar Installation"><?php echo $city ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>