	<?php
		//Northern California City Names
	$northern_california = array(
		"Northern California",
		"Acampo",
		"Acton",
		"Adelaide",
		"Aerial Acres",
		"Ahwahnee",
		"Alameda",
		"Alamo",
		"Albany",
		"Albion",
		"Alderpoint",
		"Alleghany",
		"Alta",
		"Altaville",
		"Alviso",
		"Amador City",
		"American Canyon",
		"Angels Camp",
		"Angwin",
		"Annapolis",
		"Antelope",
		"Antioch",
		"Applegate",
		"Aptos",
		"Arboga",
		"Arbuckle",
		"Arcata",
		"Argus",
		"Arnold",
		"Aromas",
		"Arroyo Grande",
		"Artois",
		"Atascadero",
		"Atherton",
		"Atwater",
		"Auberry",
		"Auburn",
		"Avery",
		"Avila Beach",
		"Badger",
		"Bakersfield",
		"Ballard",
		"Ballico",
		"Bangor",
		"Banta",
		"Bass Lake",
		"Bay Point",
		"Bayside",
		"Bear Valley",
		"Bear Valley Springs",
		"Bel Tiburon",
		"Belden",
		"Belmont",
		"Belvedere",
		"Belvedere Tiburon",
		"Ben Lomond",
		"Benicia",
		"Benton",
		"Berenda",
		"Berkeley",
		"Berry Creek",
		"Bethel Island",
		"Big Creek",
		"Big Oak Flat",
		"Big Oak Valley",
		"Big Pine",
		"Big Sur",
		"Biggs",
		"Biola",
		"Birds Landing",
		"Bishop",
		"Blackhawk",
		"Blocksburg",
		"Blue Lake",
		"Bodega",
		"Bodega Bay",
		"Bolinas",
		"Bonny Doon",
		"Boonville",
		"Boron",
		"Boulder Creek",
		"Bowman",
		"Boyes Hot Springs",
		"Bradley",
		"Branscomb",
		"Brentwood",
		"Bridgeport",
		"Bridgeville",
		"Briones",
		"Brisbane",
		"Broadmoor Vlg",
		"Broderick",
		"Brookdale",
		"Brooks",
		"Browns Valley",
		"Brownsville",
		"Bryte",
		"Buellton",
		"Burlingame",
		"Burnt Ranch",
		"Burrel",
		"Burson",
		"Butte City",
		"Butte Meadows",
		"Butte Valley",
		"Byron",
		"Caliente",
		"California City",
		"Calistoga",
		"Calpella",
		"Cambria",
		"Cameron Park",
		"Camino",
		"Camp Connell",
		"Camp Meeker",
		"Campbell",
		"Campo Seco",
		"Camptonville",
		"Cantil",
		"Cantua Creek",
		"Canyon",
		"Canyon Dam",
		"Capay",
		"Capitola",
		"Carlotta",
		"Carmel",
		"Carmel By The Sea",
		"Carmel Valley",
		"Carmichael",
		"Cartago",
		"Caruthers",
		"Casmalia",
		"Caspar",
		"Castro Valley",
		"Castroville",
		"Catheys Valley",
		"Cayucos",
		"Cazadero",
		"Cedar Ridge",
		"Ceres",
		"Chalfant",
		"Chalfant Valley",
		"Challenge",
		"Chicago Park",
		"Chico",
		"Chinese Camp",
		"Chowchilla",
		"Chualar",
		"Citrus Heights",
		"City Ranch",
		"Clarksburg",
		"Clayton",
		"Clearlake",
		"Clearlake Oaks",
		"Clearlake Park",
		"Clements",
		"Clipper Mills",
		"Cloverdale",
		"Clovis",
		"Coarsegold",
		"Cobb",
		"Cohasset",
		"Cold Springs",
		"Colfax",
		"College City",
		"Colma",
		"Coloma",
		"Columbia",
		"Colusa",
		"Comptche",
		"Concord",
		"Cool",
		"Copperopolis",
		"Corral De Tierra",
		"Corralitos",
		"Corte Madera",
		"Cotati",
		"Coulterville",
		"Courtland",
		"Covelo",
		"Coyote",
		"Crescent City",
		"Crescent Mills",
		"Cressey",
		"Creston",
		"Crockett",
		"Crowley Lake",
		"Crows Landing",
		"Crystalaire",
		"Cupertino",
		"Cutler",
		"Cutten",
		"Daly City",
		"Danville",
		"Dardanelle",
		"Darwin",
		"Davenport",
		"Davis",
		"Deer Park",
		"Del Rey",
		"Del Rey Oaks",
		"Del Sur",
		"Delhi",
		"Denair",
		"Diablo",
		"Diamond Springs",
		"Dillon Beach",
		"Dinuba",
		"Discovery Bay",
		"Dixon",
		"Dobbins",
		"Dillon Beach",
		"Dinuba Beach",
		"Discovery",
		"Dixon",
		"Dobbins",
		"Dos Palos",
		"Dos Rios",
		"Douglas Flat",
		"Downieville",
		"Drytown",
		"Dublin",
		"Duncans Mills",
		"Dunlap",
		"Dunnigan",
		"Durham",
		"Dutch Flat",
		"East Nicolaus",
		"East Palo Alto",
		"Echo Lake",
		"Eden Valley",
		"Eldridge",
		"Elizabeth Lake",
		"Elk",
		"Elk Creek",
		"Elk Grove",
		"Elmira",
		"Elverta",
		"Emerald Hills",
		"Emeryville",
		"Emigrant Gap",
		"Empire",
		"Escalon",
		"Esparto",
		"Eureka",
		"Fair Oaks",
		"Fair Play",
		"Fairfax",
		"Fairfield",
		"Farmington",
		"Feather Falls",
		"Felton",
		"Ferndale",
		"Fiddletown",
		"Fields Landing",
		"Finley",
		"Firebaugh",
		"Fiddletown",
		"Fields Landing",
		"Finley",
		"Firebaugh",
		"Fish Camp",
		"Five Points",
		"Folsom",
		"Forbestown",
		"Forest Knolls",
		"Forest Ranch",
		"Foresthill",
		"Forestville",
		"Fort Bragg",
		"Fort Hunter Liggett",
		"Fortuna",
		"Foster City",
		"Fowler",
		"Freedom",
		"Freestone",
		"Fremont",
		"French Camp",
		"Fresno",
		"Friant",
		"Fulton",
		"Galt",
		"Garberville",
		"Garden Valley",
		"Gasquet",
		"Georgetown",
		"Geyserville",
		"Gilroy",
		"Glen Ellen",
		"Glencoe",
		"Glenhaven",
		"Glenn",
		"Gold River",
		"Gold Run",
		"Golden Hills",
		"Gonzales",
		"Goodyears Bar",
		"Granite Bay",
		"Grass Valley",
		"Graton",
		"Greenbrae",
		"Greenfield",
		"Greenville",
		"Greenwood",
		"Gridley",
		"Grimes",
		"Grizzly Flats",
		"Groveland",
		"Grover Beach",
		"Guadalupe",
		"Gualala",
		"Guerneville",
		"Guinda",
		"Gustine",
		"Half Moon Bay",
		"Hamilton City",
		"Hammil Valley",
		"Harmony",
		"Hathaway Pines",
		"Havilah",
		"Hayward",
		"Healdsburg",
		"Helm",
		"Herald",
		"Hercules",
		"Heritage Ranch",
		"Hi Vista",
		"Hickman",
		"Hidden Valley Lake",
		"Hillsborough",
		"Hilltop Mall",
		"Hilmar",
		"Hollister",
		"Holt",
		"Holy City",
		"Honeydew",
		"Hood",
		"Hoopa",
		"Hopland",
		"Hornitos",
		"Hughson",
		"Hume",
		"Hydesville",
		"Independence",
		"Inverness",
		"Inyokern",
		"Ione",
		"Iowa Hill",
		"Isleton",
		"Jackson",
		"Jamestown",
		"Kentfield",
		"Kenwood",
		"Kerman",
		"Keyes",
		"King City",
		"Kings Canyon",
		"Kingsburg",
		"Kirkwood",
		"Kit Carson",
		"Klamath",
		"Kneeland",
		"Knights Ferry",
		"Knights Landing",
		"Knightsen",
		"Korbel",
		"Kyburz",
		"La Grange",
		"La Honda",
		"La Porte",
		"La Selva Beach",
		"Lafayette",
		"Lagunitas",
		"Lake Hughes",
		"Lake Los Angeles",
		"Lakeport",
		"Lakeshore",
		"Lakewood",
		"Larkfield",
		"Larkspur",
		"Lathrop",
		"Latrobe",
		"Laytonville",
		"Le Grand",
		"Lee Vining",
		"Leggett",
		"Leona Valley",
		"Liberty Farms",
		"Lincoln",
		"Linda",
		"Linden",
		"Little Lake",
		"Little River",
		"Live Oak",
		"Livermore",
		"Livingston",
		"Llano",
		"Loch Lomond",
		"Lockeford",
		"Lockwood",
		"Lodi",
		"Loleta",
		"Loma Mar",
		"Loma Rica",
		"Lompoc",
		"Lone Pine",
		"Long Barn",
		"Loomis",
		"Los Alamos",
		"Los Altos",
		"Los Banos",
		"Los Gatos",
		"Los Olivos",
		"Los Osos",
		"Lotus",
		"Lower Lake",
		"Lucerne",
		"Lyoth",
		"Mad River",
		"Madera",
		"Madison",
		"Magalia",
		"Mammoth Lakes",
		"Manchester",
		"Manteca",
		"Marina",
		"Mariposa",
		"Marshall",
		"Martell",
		"Martinez",
		"Marysville",
		"Mather",
		"Maxwell",
		"Mc Kinleyville",
		"Mcclellan",
		"Mckinleyville",
		"Mclane",
		"Meadow Valley",
		"Meadow Vista",
		"Mendocino",
		"Mendota",
		"Menlo Park",
		"Merced",
		"Meridian",
		"Mi Wuk Village",
		"Middletown",
		"Midpines",
		"Mill Valley",
		"Millbrae",
		"Milpitas",
		"Miramonte",
		"Miranda",
		"Moccasin",
		"Modesto",
		"Moffett Field",
		"Mojave",
		"Mokelumne Hill",
		"Mono Hot Springs",
		"Monolith",
		"Montara",
		"Monte Rio",
		"Monte Sereno",
		"Monte Vista",
		"Monterey",
		"Morada",
		"Moraga",
		"Morgan Hill",
		"Morro Bay",
		"Moss Beach",
		"Moss Landing",
		"Mount Aukum",
		"Mount Eden",
		"Mount Hamilton",
		"Mount Hermon",
		"Mountain House",
		"Mountain Ranch",
		"Mountain View",
		"Mt Hamilton",
		"Muir Beach",
		"Murphys",
		"Myers Flat",
		"N Highlands",
		"N Richmond",
		"N San Juan",
		"Napa",
		"Navarro",
		"Nelson",
		"Nevada City",
		"New Almaden",
		"Newark",
		"Newcastle",
		"Newman",
		"Nicasio",
		"Nice",
		"Nicolaus",
		"Nipomo",
		"Norden",
		"North Edwards",
		"North Fork",
		"North Highlands",
		"North Richmond",
		"North San Juan",
		"Novato",
		"Oakdale",
		"Oakhurst",
		"Oakland",
		"Oakley",
		"Oakville",
		"Occidental",
		"Oceano",
		"Olancha",
		"Olema",
		"Olivehurst",
		"Orange Cove",
		"Orangevale",
		"Orcutt",
		"Oregon House",
		"Orick",
		"Orinda",
		"Orland",
		"Orleans",
		"Orosi",
		"Oroville",
		"Pacheco",
		"Pacific Area Office",
		"Pacific Grove",
		"Pacific House",
		"Pacifica",
		"Paicines",
		"Pajaro",
		"Palermo",
		"Palmdale",
		"Palo Alto",
		"Palomar Park",
		"Paradise",
		"Parkfield",
		"Parlier",
		"Paso Robles",
		"Patterson",
		"Pearsonville",
		"Pebble Beach",
		"Penn Valley",
		"Penngrove",
		"Penryn",
		"Permanente",
		"Pescadero",
		"Petaluma",
		"Petrolia",
		"Phillipsville",
		"Philo",
		"Piedmont",
		"Piedra",
		"Piercy",
		"Pilot Hill",
		"Pine Grove",
		"Pinecrest",
		"Pinedale",
		"Pinole",
		"Pioneer",
		"Pismo Beach",
		"Pittsburg",
		"Placerville",
		"Planada",
		"Pleasant Grove",
		"Pleasant Hill",
		"Pleasanton",
		"Plumas Lake",
		"Plymouth",
		"Point Arena",
		"Point Richmond",
		"Pollock Pines",
		"Pollock Pines",
		"Pope Valley",
		"Port Costa",
		"Portola Valley",
		"Potter Valley",
		"Prather",
		"Princeton",
		"Prunedale",
		"Pulga",
		"Pumpkin Center",
		"Quincy",
		"Rackerby",
		"Ragged Point",
		"Rail Road Flat",
		"Raisin City",
		"Rancho Cordova",
		"Rancho Murieta",
		"Rancho Suey",
		"Randsburg",
		"Raymond",
		"Red Mountain",
		"Redcrest",
		"Redding",
		"Redway",
		"Redwood City",
		"Redwood Estates",
		"Redwood Valley",
		"Reedley",
		"Represa",
		"Rescue",
		"Richmond",
		"Richvale",
		"Ridgecrest",
		"Rio Dell",
		"Rio Linda",
		"Rio Nido",
		"Rio Oso",
		"Rio Vista",
		"Ripon",
		"River Pines",
		"Riverbank",
		"Riverdale",
		"Robbins",
		"Rocklin",
		"Rodeo",
		"Rohnert Park",
		"Rosamond",
		"Roseville",
		"Ross",
		"Royal Oaks",
		"Rumsey",
		"Russian River",
		"Rutherford",
		"Ryde",
		"Sacramento",
		"Saint Helena",
		"Salida",
		"Salinas",
		"Salyer",
		"Samoa",
		"San Andreas",
		"San Anselmo",
		"San Ardo",
		"San Bruno",
		"San Carlos",
		"San Francisco",
		"San Geronimo",
		"San Gregorio",
		"San Joaquin",
		"San Jose",
		"San Juan Bautista",
		"San Leandro",
		"San Lorenzo",
		"San Lucas",
		"San Luis Obispo",
		"San Martin",
		"San Mateo",
		"San Miguel",
		"San Pablo",
		"San Quentin",
		"San Rafael",
		"San Ramon",
		"San Simeon",
		"Sand City",
		"Sanger",
		"Santa Clara",
		"Santa Cruz",
		"Santa Margarita",
		"Santa Maria",
		"Santa Nella",
		"Santa Rita Park",
		"Santa Rosa",
		"Santa Ynez",
		"Saratoga",
		"Sausalito",
		"Scotia",
		"Scotts Valley",
		"Seaside",
		"Sebastopol",
		"Selma",
		"Sequoyah",
		"Shandon",
		"Shaver Lake",
		"Sheep Ranch",
		"Shell Beach",
		"Sheridan",
		"Shingle Springs",
		"Sloughhouse",
		"Smartsville",
		"Smith River",
		"Snelling",
		"Soda Springs",
		"Soledad",
		"Solvang",
		"Somerset",
		"Somes Bar",
		"Sonoma",
		"Sonora",
		"Soquel",
		"Soulsbyville",
		"South Dos Palos",
		"South San Francisco",
		"Spanish Flat",
		"Spreckels",
		"Spring Garden",
		"Squaw Valley",
		"Stallion Springs",
		"Standard",
		"Stanford",
		"Stevinson",
		"Stewarts Point",
		"Stinson Beach",
		"Stirling City",
		"Stockton",
		"Stonyford",
		"Strawberry Valley",
		"Suisun City",
		"Sultana",
		"Sun Village",
		"Sunnyvale",
		"Sunol",
		"Sunrise Oaks",
		"Sutter",
		"Sutter Creek",
		"Swall Meadows",
		"Talmage",
		"Taylorsville",
		"Tehachapi",
		"Templeton",
		"The Sea Ranch",
		"Thornton",
		"Tiburon",
		"Tollhouse",
		"Tomales",
		"Toms Place",
		"Tracy",
		"Tranquillity",
		"Traver",
		"Tres Pinos",
		"Trestle Glen",
		"Trinidad",
		"Trona",
		"Trowbridge",
		"Tuolumne",
		"Tuolumne Meadows",
		"Turlock",
		"Twain",
		"Twain Harte",
		"Twin Bridges",
		"Ukiah",
		"Union City",
		"Upper Lake",
		"Vacaville",
		"Vallecito",
		"Vallejo",
		"Valley Ford",
		"Valley Home",
		"Valley Springs",
		"Valyermo",
		"Vernalis",
		"Victor",
		"Villa Grande",
		"Vineburg",
		"Volcano",
		"Wallace",
		"Walnut Creek",
		"Walnut Grove",
		"Washington",
		"Waterford",
		"Watsonville",
		"Wawona",
		"Weimar",
		"Weott",
		"West Linda",
		"West Menlo Park",
		"West Point",
		"West Sacramento",
		"Westley",
		"Westport",
		"Wheatland",
		"Whitethorn",
		"Williams",
		"Willits",
		"Willow Creek",
		"Willow Springs",
		"Willows",
		"Wilseyville",
		"Wilton",
		"Windsor",
		"Winters",
		"Winton",
		"Wishon",
		"Witter Springs",
		"Woodacre",
		"Woodbridge",
		"Woodland",
		"Woodside",
		"Yankee Hill",
		"Yettem",
		"Yolo",
		"Yorkville",
		"Yountville",
		"Yuba City",
		"Zamora",
		"Zenia",
	); ?>

	<div class="p-5 m-5">
		<h2 class="text-center pb-5">Northern California Locations</h2>
		<ul class="list-of-cities">
			<?php foreach($northern_california as $city) : ?>
				<li><a href="/california-<?php echo strtolower(str_replace(" ", "-", $city)); ?>-solar-installation/"
					title="<?php echo $city ?> Solar Installation"><?php echo $city ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>