<?php 
	//Southern California City Names 
$southern_california = array(
	"Aliso Viejo",
	"Anaheim",
	"Atwood",
	"Azusa",
	"Baldwin Park",
	"Beaumont",
	"Big Bear City",
	"Big Bear Lake",
	"Bloomington",
	"Blue Jay",
	"Brea",
	"Bryn Mawr",
	"Calimesa",
	"Capistrano Beach",
	"Cedar Glen",
	"Cedarpines Park",
	"Chino",
	"Chino Hills",
	"Claremont",
	"Colton",
	"Corona",
	"Corona Del Mar",
	"Costa Mesa",
	"Covina",
	"Crestline",
	"Dana Point",
	"Diamond Bar",
	"Duarte",
	"East Irvine",
	"El Toro",
	"Fawnskin",
	"Fontana",
	"Foothill Ranch",
	"Fountain Valley",
	"Fullerton",
	"Garden Grove",
	"Glendora",
	"Grand Terrace",
	"Green Valley Lake",
	"Guasti",
	"Hacienda Heights",
	"Hemet",
	"Highland",
	"Homeland",
	"Huntington Beach",
	"Inland Empire",
	"Irvine",
	"Jurupa Valley",
	"La Habra",
	"La Puente",
	"La Verne",
	"Ladera Ranch",
	"Laguna Beach",
	"Laguna Hills",
	"Laguna Niguel",
	"Laguna Woods",
	"Lake Arrowhead",
	"Lake Elsinore",
	"Lake Forest",
	"Loma Linda",
	"Lytle Creek",
	"Menifee",
	"Mentone",
	"Midway City",
	"Mira Loma",
	"Mission Viejo",
	"Monrovia",
	"Montclair",
	"Moreno Valley",
	"Mt Baldy",
	"Murrieta",
	"Newport Beach",
	"Newport Coast",
	"Norco",
	"Nuevo",
	"Ontario",
	"Orange",
	"Patton",
	"Perris",
	"Placentia",
	"Pomona",
	"Rancho Cucamonga",
	"Rancho Santa Margarita",
	"Redlands",
	"Rialto",
	"Rimforest",
	"Rowland Heights",
	"Running Springs",
	"San Bernardino",
	"San Diego County",
	"San Clemente",
	"San Dimas",
	"San Jacinto",
	"San Juan Capistrano",
	"Santa Ana",
	"Silverado",
	"Skyforest",
	"Southern California",
	"Temecula",
	"Temecula Valley",
	"Trabuco Canyon",
	"Tustin",
	"Twin Peaks",
	"Upland",
	"Valyermo",
	"Villa Park",
	"Walnut",
	"West Covina",
	"Westminster",
	"Wildomar",
	"Winchester",
	"Wrightwood",
	"Yorba Linda",
	"Yucaipa",
);
?>

<div class="p-5 m-5">
	<h2 class="text-center pb-5">Southern California Locations</h2>
	<ul class="list-of-cities">
		<?php foreach($southern_california as $city) : ?>
			<li><a href="/california-<?php echo strtolower(str_replace(" ", "-", $city)); ?>-solar-installation/"
				title="<?php echo $city ?> Solar Installation"><?php echo $city ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>