<?php

/**
* Template Name: City Pages
*
*
* @package WordPress

* @since 1.0.0
*/

?>

<?php echo get_template_part('partials/head'); ?>
<style>
  .list-of-cities {
    margin: 0;
    padding: 0;
    columns: 210px auto;
    column-gap: 8px;
    list-style: none;
  }

  .list-of-cities li {
    padding: 2px 4px;
    display: inline-block;
    width: 100%;
  }

  .column1 {
    float: left;
    width: 25%;
  }

  .row1:after {
    content: "";
    display: table;
    clear: both;
  }

  /* Cards */
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    transition: 0.3s;
    border-radius: 5px;
    margin: 5px;
    padding: 10px;
    background-color: white;
  }

  .card:hover {
    box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
  }

  .container {
    padding: 2px 16px;
  }

  a.solar_pricing {
    display: block;
    position: relative;
    top: -120px;
    visibility: hidden;
  }

  @media (max-width: 812px) {
    .column1 {
      float: none;
      width: 100%;
      text-align: center;
    }

    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      transition: 0.3s;
      border-radius: 5px;
      /* margin: 5px; */
      margin-top: 5px;
      margin-left: 5px;
      margin-right: 5px;
      margin-bottom: 20px;
      padding: 10px;
      background-color: white;
    }
  }

  @media screen and (max-width: 600px) {
    .column {
      width: 100%;
    }
  }

  @media (max-width: 575.98px) {
    .column1 {
      float: none;
      width: 100%;
    }

    .p-left {
      padding-left: 1px;
      text-align: center;
    }

    .p-left img {
      display: none;
    }

    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      transition: 0.3s;
      border-radius: 5px;
      /* margin: 5px; */
      margin-top: 5px;
      margin-left: 5px;
      margin-right: 5px;
      margin-bottom: 20px;
      padding: 10px;
      background-color: white;
    }
  }


  @media (max-width:428px) {
    .list-of-cities {
      margin: 0;
      padding: 0;
      columns: 80px auto;
      column-gap: 8px;
      list-style: none;
    }

    .list-of-cities li {
      padding: 2px 4px;
      display: inline-block;
      width: 100%;
    }
  }
</style>
</head>
<body>

  <!-- navigation -->
  <?php echo get_template_part('partials/nav'); ?>
  <!-- end navigation -->
  <main role="main" class="page-header">
    <section>
      <?php echo get_template_part('partials/forms/collapse_form'); ?>
    </section>

    <section class="city-page-header">
      <h1 class="pt-5 display-4 text-white">Solar Installation Company in <?php the_field('city_name'); ?></h1>
      <h2 class="text-white">Do You Need Solar Panels Installed in <?php the_field('city_name'); ?>?</h2>
      <a href="#fullscreenModal" class="btn btn-light mt-4 font-weight-bold" data-toggle="modal">
        <i class="far fa-envelope-open" aria-hidden="true"></i>
      &nbsp;Get A Free Solar Quote</a>
    </section>

    <section>
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <h2 class="pt-5 display-4">Buying and Financing
              <?php the_field('city_name') ?> Solar</h2>
            </div>
          </div>
          <div class="card-deck pt-5 pb-5">
            <div class="card card-shadow">
              <div class="card-body">
                <h3 class="card-title text-center"><?php the_field('city_name') ?> Solar<br>Cash Purchase</h3>
              </div>
              <p class="card-footer text-center">
                <a class="btn btn-orange" href="" title="Solar Cash Purchasing Options">
                  <i class="fa fa-graduation-cap" aria-hidden="true"></i> 
                  &nbsp;LEARN MORE
                </a>
              </p>
            </div>
            <div class="card card-shadow">
              <div class="card-body">
                <h3 class="card-title text-center">Finance Solar<br>in
                  <?php the_field('city_name'); ?></h3>
                </div>
                <p class="card-footer text-center">
                  <a class="btn btn-orange" href="" title="Solar Cash Purchasing Options">
                    <i class="fa fa-graduation-cap" aria-hidden="true"></i> 
                    &nbsp;LEARN MORE
                  </a>
                </p>
              </div>
              <div class="card card-shadow">
                <div class="card-body">
                  <h3 class="card-title text-center">Lease Solar<br>in
                    <?php the_field('city_name'); ?></h3>
                  </div>
                  <p class="card-footer text-center">
                    <a class="btn btn-orange" href="" title="Solar Cash Purchasing Options">
                      <i class="fa fa-graduation-cap" aria-hidden="true"></i> 
                      &nbsp;LEARN MORE
                    </a>
                  </p>
                </div>
                <div class="card card-shadow">
                  <div class="card-body">
                    <h3 class="card-title text-center"><?php the_field('city_name'); ?><br>Solar PPA</h3>
                  </div>
                  <p class="card-footer text-center">
                    <a class="btn btn-orange" href="" title="Solar Cash Purchasing Options">
                      <i class="fa fa-graduation-cap" aria-hidden="true"></i> 
                      &nbsp;LEARN MORE
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </section>

          <!-- Cash Purchase -->
          <?php echo get_template_part('partials/city-pages/financing/cash-purchase'); ?>
          <!-- Finance -->
          <?php echo get_template_part('partials/city-pages/financing/financing'); ?>
          <!-- Lease -->
          <?php echo get_template_part('partials/city-pages/financing/lease'); ?>
          <!-- PPA -->
          <?php echo get_template_part('partials/city-pages/financing/ppa'); ?>
          <hr>

          <!-- solar energy savings -->
          <section class="content-visibility">
            <div class="container">
              <div class="row">
                <div class="col p-5 text-center">
                  <h2><?php the_field('city_name'); ?> Solar Energy Savings</h2>
                  <img style="padding:20px;" class="center img-fluid" alt="Sungevity"
                  src="<?php bloginfo('template_directory'); ?>/img/UT-SavingsGraph-00025e1f.jpg?v=2" loading="lazy">
                  <div>
                    <small>* According to data from the average Sungevity solar system in all the areas we
                      serviced between 2010 and 2015.
                      Images are for illustrative purposes only. Actual savings vary by customer. See
                      sungevity.com/savings for details on how we calculate savings.
                    </small> 
                  </div>
                  <div class="pt-5">
                    <a class="btn btn-orange" href="<?php get_home_url(); ?>/get-your-iquote/"><i class="fa fa-check-square-o " aria-hidden="true"></i> Switch To Solar</a>
                  </div>
                </div>
              </div>
            </div>  
          </section>

          <!-- FAQs -->
          <?php echo get_template_part('partials/city-pages/faqs/faqs'); ?>

          <section class="content-visibility d-none d-sm-block">
            <div class="row">
              <div class="col-md-6 mt-5">
                <div class="container">
                  <div class="col-md-12 p-5 mt-5 width-50 move_left">
                    <h2>A system designed for <?php the_field('city_name'); ?> Solar Customers</h2>
                    <p class="d-block text-center text-md-left">
                      <a href="#fullscreenModal" class="btn btn-orange mt-4 font-weight-bold" data-toggle="modal">
                        <i class="far fa-envelope-open" aria-hidden="true"></i>
                      &nbsp;Get A Free Solar Quote</a>
                    </p>
                  </div>
                </div>
              </div>
              <div class="lazy col float-right right-family-background2" style="display: block; background-image: url('<?php bloginfo('template_directory'); ?>/img/backgrounds/family-background-2.jpg')">
              </div>
            </div>
          </section>

          <section class="content-visibility d-none d-sm-block">
            <div class="row">
              <div class="col-md-6 mt-5">
                <div class="container">
                  <div class="col-md-12 p-5 mt-5 width-50 move_left">
                    <h2>Watch your <?php the_field('city_name'); ?> solar system perform in real-time</h2>
                    <p class="d-block text-center text-md-left">
                      <a href="#fullscreenModal" class="btn btn-orange mt-4 font-weight-bold" data-toggle="modal">
                        <i class="far fa-envelope-open" aria-hidden="true"></i>
                      &nbsp;Get A Free Solar Quote</a>
                    </p>
                  </div>
                </div>
              </div>
              <div class="lazy col float-right right-family-background2" style="display: block; background-image: url('<?php bloginfo('template_directory'); ?>/img/solar-mobile-savings.jpg')">
              </div>
            </div>
          </section>

          <!-- commercial -->
          <section class="lazy sungevity-commercial-background content-visibility" data-src="<?php bloginfo('template_directory'); ?>/img/backgrounds/sungevity-solar-installer.jpg">
            <div class="row">
              <div class="col-md-4 p-5 move_left">
                <h3 class="text-dark">Looking for <?php the_field('city_name'); ?> Commercial Solar?</h3>
                <p>Our team has extensive <?php the_field('city_name'); ?> commercial solar experience to guide you to the right power solution and your dedicated Project Manager will take care of all the details.</p>
                <div class="col-md-12 text-center text-md-left p-2">
                  <a href="" class="btn btn-orange mt-4 font-weight-bold">
                    <i class="far fa-envelope-open" aria-hidden="true"></i>
                  &nbsp;Get A Free Solar Quote</a>
                </div>
              </div>
              <div class="col-md-5"></div>    
            </div>
          </section>

          <?php
    //Northern California City Names
          $northern_california = array(
            "Northern California",
            "Acampo",
            "Acton",
            "Adelaide",
            "Aerial Acres",
            "Ahwahnee",
            "Alameda",
            "Alamo",
            "Albany",
            "Albion",
            "Alderpoint",
            "Alleghany",
            "Alta",
            "Altaville",
            "Alviso",
            "Amador City",
            "American Canyon",
            "Angels Camp",
            "Angwin",
            "Annapolis",
            "Antelope",
            "Antioch",
            "Applegate",
            "Aptos",
            "Arboga",
            "Arbuckle",
            "Arcata",
            "Argus",
            "Arnold",
            "Aromas",
            "Arroyo Grande",
            "Artois",
            "Atascadero",
            "Atherton",
            "Atwater",
            "Auberry",
            "Auburn",
            "Avery",
            "Avila Beach",
            "Badger",
            "Bakersfield",
            "Ballard",
            "Ballico",
            "Bangor",
            "Banta",
            "Bass Lake",
            "Bay Point",
            "Bayside",
            "Bear Valley",
            "Bear Valley Springs",
            "Bel Tiburon",
            "Belden",
            "Belmont",
            "Belvedere",
            "Belvedere Tiburon",
            "Ben Lomond",
            "Benicia",
            "Benton",
            "Berenda",
            "Berkeley",
            "Berry Creek",
            "Bethel Island",
            "Big Creek",
            "Big Oak Flat",
            "Big Oak Valley",
            "Big Pine",
            "Big Sur",
            "Biggs",
            "Biola",
            "Birds Landing",
            "Bishop",
            "Blackhawk",
            "Blocksburg",
            "Blue Lake",
            "Bodega",
            "Bodega Bay",
            "Bolinas",
            "Bonny Doon",
            "Boonville",
            "Boron",
            "Boulder Creek",
            "Bowman",
            "Boyes Hot Springs",
            "Bradley",
            "Branscomb",
            "Brentwood",
            "Bridgeport",
            "Bridgeville",
            "Briones",
            "Brisbane",
            "Broadmoor Vlg",
            "Broderick",
            "Brookdale",
            "Brooks",
            "Browns Valley",
            "Brownsville",
            "Bryte",
            "Buellton",
            "Burlingame",
            "Burnt Ranch",
            "Burrel",
            "Burson",
            "Butte City",
            "Butte Meadows",
            "Butte Valley",
            "Byron",
            "Caliente",
            "California City",
            "Calistoga",
            "Calpella",
            "Cambria",
            "Cameron Park",
            "Camino",
            "Camp Connell",
            "Camp Meeker",
            "Campbell",
            "Campo Seco",
            "Camptonville",
            "Cantil",
            "Cantua Creek",
            "Canyon",
            "Canyon Dam",
            "Capay",
            "Capitola",
            "Carlotta",
            "Carmel",
            "Carmel By The Sea",
            "Carmel Valley",
            "Carmichael",
            "Cartago",
            "Caruthers",
            "Casmalia",
            "Caspar",
            "Castro Valley",
            "Castroville",
            "Catheys Valley",
            "Cayucos",
            "Cazadero",
            "Cedar Ridge",
            "Ceres",
            "Chalfant",
            "Chalfant Valley",
            "Challenge",
            "Chicago Park",
            "Chico",
            "Chinese Camp",
            "Chowchilla",
            "Chualar",
            "Citrus Heights",
            "City Ranch",
            "Clarksburg",
            "Clayton",
            "Clearlake",
            "Clearlake Oaks",
            "Clearlake Park",
            "Clements",
            "Clipper Mills",
            "Cloverdale",
            "Clovis",
            "Coarsegold",
            "Cobb",
            "Cohasset",
            "Cold Springs",
            "Colfax",
            "College City",
            "Colma",
            "Coloma",
            "Columbia",
            "Colusa",
            "Comptche",
            "Concord",
            "Cool",
            "Copperopolis",
            "Corral De Tierra",
            "Corralitos",
            "Corte Madera",
            "Cotati",
            "Coulterville",
            "Courtland",
            "Covelo",
            "Coyote",
            "Crescent City",
            "Crescent Mills",
            "Cressey",
            "Creston",
            "Crockett",
            "Crowley Lake",
            "Crows Landing",
            "Crystalaire",
            "Cupertino",
            "Cutler",
            "Cutten",
            "Daly City",
            "Danville",
            "Dardanelle",
            "Darwin",
            "Davenport",
            "Davis",
            "Deer Park",
            "Del Rey",
            "Del Rey Oaks",
            "Del Sur",
            "Delhi",
            "Denair",
            "Diablo",
            "Diamond Springs",
            "Dillon Beach",
            "Dinuba",
            "Discovery Bay",
            "Dixon",
            "Dobbins",
            "Dillon Beach",
            "Dinuba Beach",
            "Discovery",
            "Dixon",
            "Dobbins",
            "Dos Palos",
            "Dos Rios",
            "Douglas Flat",
            "Downieville",
            "Drytown",
            "Dublin",
            "Duncans Mills",
            "Dunlap",
            "Dunnigan",
            "Durham",
            "Dutch Flat",
            "East Nicolaus",
            "East Palo Alto",
            "Echo Lake",
            "Eden Valley",
            "Eldridge",
            "Elizabeth Lake",
            "Elk",
            "Elk Creek",
            "Elk Grove",
            "Elmira",
            "Elverta",
            "Emerald Hills",
            "Emeryville",
            "Emigrant Gap",
            "Empire",
            "Escalon",
            "Esparto",
            "Eureka",
            "Fair Oaks",
            "Fair Play",
            "Fairfax",
            "Fairfield",
            "Farmington",
            "Feather Falls",
            "Felton",
            "Ferndale",
            "Fiddletown",
            "Fields Landing",
            "Finley",
            "Firebaugh",
            "Fiddletown",
            "Fields Landing",
            "Finley",
            "Firebaugh",
            "Fish Camp",
            "Five Points",
            "Folsom",
            "Forbestown",
            "Forest Knolls",
            "Forest Ranch",
            "Foresthill",
            "Forestville",
            "Fort Bragg",
            "Fort Hunter Liggett",
            "Fortuna",
            "Foster City",
            "Fowler",
            "Freedom",
            "Freestone",
            "Fremont",
            "French Camp",
            "Fresno",
            "Friant",
            "Fulton",
            "Galt",
            "Garberville",
            "Garden Valley",
            "Gasquet",
            "Georgetown",
            "Geyserville",
            "Gilroy",
            "Glen Ellen",
            "Glencoe",
            "Glenhaven",
            "Glenn",
            "Gold River",
            "Gold Run",
            "Golden Hills",
            "Gonzales",
            "Goodyears Bar",
            "Granite Bay",
            "Grass Valley",
            "Graton",
            "Greenbrae",
            "Greenfield",
            "Greenville",
            "Greenwood",
            "Gridley",
            "Grimes",
            "Grizzly Flats",
            "Groveland",
            "Grover Beach",
            "Guadalupe",
            "Gualala",
            "Guerneville",
            "Guinda",
            "Gustine",
            "Half Moon Bay",
            "Hamilton City",
            "Hammil Valley",
            "Harmony",
            "Hathaway Pines",
            "Havilah",
            "Hayward",
            "Healdsburg",
            "Helm",
            "Herald",
            "Hercules",
            "Heritage Ranch",
            "Hi Vista",
            "Hickman",
            "Hidden Valley Lake",
            "Hillsborough",
            "Hilltop Mall",
            "Hilmar",
            "Hollister",
            "Holt",
            "Holy City",
            "Honeydew",
            "Hood",
            "Hoopa",
            "Hopland",
            "Hornitos",
            "Hughson",
            "Hume",
            "Hydesville",
            "Independence",
            "Inverness",
            "Inyokern",
            "Ione",
            "Iowa Hill",
            "Isleton",
            "Jackson",
            "Jamestown",
            "Kentfield",
            "Kenwood",
            "Kerman",
            "Keyes",
            "King City",
            "Kings Canyon",
            "Kingsburg",
            "Kirkwood",
            "Kit Carson",
            "Klamath",
            "Kneeland",
            "Knights Ferry",
            "Knights Landing",
            "Knightsen",
            "Korbel",
            "Kyburz",
            "La Grange",
            "La Honda",
            "La Porte",
            "La Selva Beach",
            "Lafayette",
            "Lagunitas",
            "Lake Hughes",
            "Lake Los Angeles",
            "Lakeport",
            "Lakeshore",
            "Lakewood",
            "Larkfield",
            "Larkspur",
            "Lathrop",
            "Latrobe",
            "Laytonville",
            "Le Grand",
            "Lee Vining",
            "Leggett",
            "Leona Valley",
            "Liberty Farms",
            "Lincoln",
            "Linda",
            "Linden",
            "Little Lake",
            "Little River",
            "Live Oak",
            "Livermore",
            "Livingston",
            "Llano",
            "Loch Lomond",
            "Lockeford",
            "Lockwood",
            "Lodi",
            "Loleta",
            "Loma Mar",
            "Loma Rica",
            "Lompoc",
            "Lone Pine",
            "Long Barn",
            "Loomis",
            "Los Alamos",
            "Los Altos",
            "Los Banos",
            "Los Gatos",
            "Los Olivos",
            "Los Osos",
            "Lotus",
            "Lower Lake",
            "Lucerne",
            "Lyoth",
            "Mad River",
            "Madera",
            "Madison",
            "Magalia",
            "Mammoth Lakes",
            "Manchester",
            "Manteca",
            "Marina",
            "Mariposa",
            "Marshall",
            "Martell",
            "Martinez",
            "Marysville",
            "Mather",
            "Maxwell",
            "Mc Kinleyville",
            "Mcclellan",
            "Mckinleyville",
            "Mclane",
            "Meadow Valley",
            "Meadow Vista",
            "Mendocino",
            "Mendota",
            "Menlo Park",
            "Merced",
            "Meridian",
            "Mi Wuk Village",
            "Middletown",
            "Midpines",
            "Mill Valley",
            "Millbrae",
            "Milpitas",
            "Miramonte",
            "Miranda",
            "Moccasin",
            "Modesto",
            "Moffett Field",
            "Mojave",
            "Mokelumne Hill",
            "Mono Hot Springs",
            "Monolith",
            "Montara",
            "Monte Rio",
            "Monte Sereno",
            "Monte Vista",
            "Monterey",
            "Morada",
            "Moraga",
            "Morgan Hill",
            "Morro Bay",
            "Moss Beach",
            "Moss Landing",
            "Mount Aukum",
            "Mount Eden",
            "Mount Hamilton",
            "Mount Hermon",
            "Mountain House",
            "Mountain Ranch",
            "Mountain View",
            "Mt Hamilton",
            "Muir Beach",
            "Murphys",
            "Myers Flat",
            "N Highlands",
            "N Richmond",
            "N San Juan",
            "Napa",
            "Navarro",
            "Nelson",
            "Nevada City",
            "New Almaden",
            "Newark",
            "Newcastle",
            "Newman",
            "Nicasio",
            "Nice",
            "Nicolaus",
            "Nipomo",
            "Norden",
            "North Edwards",
            "North Fork",
            "North Highlands",
            "North Richmond",
            "North San Juan",
            "Novato",
            "Oakdale",
            "Oakhurst",
            "Oakland",
            "Oakley",
            "Oakville",
            "Occidental",
            "Oceano",
            "Olancha",
            "Olema",
            "Olivehurst",
            "Orange Cove",
            "Orangevale",
            "Orcutt",
            "Oregon House",
            "Orick",
            "Orinda",
            "Orland",
            "Orleans",
            "Orosi",
            "Oroville",
            "Pacheco",
            "Pacific Area Office",
            "Pacific Grove",
            "Pacific House",
            "Pacifica",
            "Paicines",
            "Pajaro",
            "Palermo",
            "Palmdale",
            "Palo Alto",
            "Palomar Park",
            "Paradise",
            "Parkfield",
            "Parlier",
            "Paso Robles",
            "Patterson",
            "Pearsonville",
            "Pebble Beach",
            "Penn Valley",
            "Penngrove",
            "Penryn",
            "Permanente",
            "Pescadero",
            "Petaluma",
            "Petrolia",
            "Phillipsville",
            "Philo",
            "Piedmont",
            "Piedra",
            "Piercy",
            "Pilot Hill",
            "Pine Grove",
            "Pinecrest",
            "Pinedale",
            "Pinole",
            "Pioneer",
            "Pismo Beach",
            "Pittsburg",
            "Placerville",
            "Planada",
            "Pleasant Grove",
            "Pleasant Hill",
            "Pleasanton",
            "Plumas Lake",
            "Plymouth",
            "Point Arena",
            "Point Richmond",
            "Pollock Pines",
            "Pollock Pines",
            "Pope Valley",
            "Port Costa",
            "Portola Valley",
            "Potter Valley",
            "Prather",
            "Princeton",
            "Prunedale",
            "Pulga",
            "Pumpkin Center",
            "Quincy",
            "Rackerby",
            "Ragged Point",
            "Rail Road Flat",
            "Raisin City",
            "Rancho Cordova",
            "Rancho Murieta",
            "Rancho Suey",
            "Randsburg",
            "Raymond",
            "Red Mountain",
            "Redcrest",
            "Redding",
            "Redway",
            "Redwood City",
            "Redwood Estates",
            "Redwood Valley",
            "Reedley",
            "Represa",
            "Rescue",
            "Richmond",
            "Richvale",
            "Ridgecrest",
            "Rio Dell",
            "Rio Linda",
            "Rio Nido",
            "Rio Oso",
            "Rio Vista",
            "Ripon",
            "River Pines",
            "Riverbank",
            "Riverdale",
            "Robbins",
            "Rocklin",
            "Rodeo",
            "Rohnert Park",
            "Rosamond",
            "Roseville",
            "Ross",
            "Royal Oaks",
            "Rumsey",
            "Russian River",
            "Rutherford",
            "Ryde",
            "Sacramento",
            "Saint Helena",
            "Salida",
            "Salinas",
            "Salyer",
            "Samoa",
            "San Andreas",
            "San Anselmo",
            "San Ardo",
            "San Bruno",
            "San Carlos",
            "San Francisco",
            "San Geronimo",
            "San Gregorio",
            "San Joaquin",
            "San Jose",
            "San Juan Bautista",
            "San Leandro",
            "San Lorenzo",
            "San Lucas",
            "San Luis Obispo",
            "San Martin",
            "San Mateo",
            "San Miguel",
            "San Pablo",
            "San Quentin",
            "San Rafael",
            "San Ramon",
            "San Simeon",
            "Sand City",
            "Sanger",
            "Santa Clara",
            "Santa Cruz",
            "Santa Margarita",
            "Santa Maria",
            "Santa Nella",
            "Santa Rita Park",
            "Santa Rosa",
            "Santa Ynez",
            "Saratoga",
            "Sausalito",
            "Scotia",
            "Scotts Valley",
            "Seaside",
            "Sebastopol",
            "Selma",
            "Sequoyah",
            "Shandon",
            "Shaver Lake",
            "Sheep Ranch",
            "Shell Beach",
            "Sheridan",
            "Shingle Springs",
            "Sloughhouse",
            "Smartsville",
            "Smith River",
            "Snelling",
            "Soda Springs",
            "Soledad",
            "Solvang",
            "Somerset",
            "Somes Bar",
            "Sonoma",
            "Sonora",
            "Soquel",
            "Soulsbyville",
            "South Dos Palos",
            "South San Francisco",
            "Spanish Flat",
            "Spreckels",
            "Spring Garden",
            "Squaw Valley",
            "Stallion Springs",
            "Standard",
            "Stanford",
            "Stevinson",
            "Stewarts Point",
            "Stinson Beach",
            "Stirling City",
            "Stockton",
            "Stonyford",
            "Strawberry Valley",
            "Suisun City",
            "Sultana",
            "Sun Village",
            "Sunnyvale",
            "Sunol",
            "Sunrise Oaks",
            "Sutter",
            "Sutter Creek",
            "Swall Meadows",
            "Talmage",
            "Taylorsville",
            "Tehachapi",
            "Templeton",
            "The Sea Ranch",
            "Thornton",
            "Tiburon",
            "Tollhouse",
            "Tomales",
            "Toms Place",
            "Tracy",
            "Tranquillity",
            "Traver",
            "Tres Pinos",
            "Trestle Glen",
            "Trinidad",
            "Trona",
            "Trowbridge",
            "Tuolumne",
            "Tuolumne Meadows",
            "Turlock",
            "Twain",
            "Twain Harte",
            "Twin Bridges",
            "Ukiah",
            "Union City",
            "Upper Lake",
            "Vacaville",
            "Vallecito",
            "Vallejo",
            "Valley Ford",
            "Valley Home",
            "Valley Springs",
            "Valyermo",
            "Vernalis",
            "Victor",
            "Villa Grande",
            "Vineburg",
            "Volcano",
            "Wallace",
            "Walnut Creek",
            "Walnut Grove",
            "Washington",
            "Waterford",
            "Watsonville",
            "Wawona",
            "Weimar",
            "Weott",
            "West Linda",
            "West Menlo Park",
            "West Point",
            "West Sacramento",
            "Westley",
            "Westport",
            "Wheatland",
            "Whitethorn",
            "Williams",
            "Willits",
            "Willow Creek",
            "Willow Springs",
            "Willows",
            "Wilseyville",
            "Wilton",
            "Windsor",
            "Winters",
            "Winton",
            "Wishon",
            "Witter Springs",
            "Woodacre",
            "Woodbridge",
            "Woodland",
            "Woodside",
            "Yankee Hill",
            "Yettem",
            "Yolo",
            "Yorkville",
            "Yountville",
            "Yuba City",
            "Zamora",
            "Zenia",
          );

    //Central California City Names

$central_california = array(
  "Acton",
  "Ahwahnee",
  "Armona",
  "Arvin",
  "Atwater",
  "Auberry",
  "Avenal",
  "Badger",
  "Bakersfield",
  "Ballico",
  "Bass lake",
  "Benton",
  "Big pine",
  "Bishop",
  "Bodfish",
  "Boron",
  "Buttonwillow",
  "Caliente",
  "California city",
  "Caruthers",
  "Ceres",
  "Chowchilla",
  "Clovis",
  "Coalinga",
  "Coarsegold",
  "Columbia",
  "Corcoran",
  "Coulterville",
  "Crows landing",
  "Cutler",
  "Del rey",
  "Delano",
  "Delhi",
  "Denair",
  "Dinuba",
  "Dos palos",
  "Dunlap",
  "Earlimart",
  "Edwards",
  "El nido",
  "Escalon",
  "Exeter",
  "Farmersville",
  "Fellows",
  "Firebaugh",
  "Fowler",
  "Frazier park",
  "Fresno",
  "Friant",
  "Glennville",
  "Groveland",
  "Gustine",
  "Hanford",
  "Hickman",
  "Hilmar",
  "Hollister",
  "Hughson",
  "Hume",
  "Independence",
  "Inyokern",
  "Ivanhoe",
  "Jamestown",
  "June lake",
  "Keene",
  "Kerman",
  "Kernville",
  "Keyes",
  "Kingsburg",
  "La grange",
  "Lake hughes",
  "Lake isabella",
  "Lamont",
  "Lancaster",
  "Lathrop",
  "Laton",
  "Legrand",
  "Lemoore",
  "Lindsay",
  "Littlerock",
  "Livingston",
  "Llano",
  "Lodi",
  "Lompoc",
  "Lone pine",
  "Long barn",
  "Los banos",
  "Lost hills",
  "Madera",
  "Mammoth lakes",
  "Manteca",
  "Maricopa",
  "Mariposa",
  "Mcfarland",
  "Mendota",
  "Merced",
  "Miramonte",
  "Mi-wuk village",
  "Modesto",
  "Mojave",
  "Monterey",
  "Newman",
  "North fork",
  "Oakdale",
  "Oakhurst",
  "O'neals",
  "Onyx",
  "Orange cove",
  "Orosi",
  "Palmdale",
  "Parlier",
  "Patterson",
  "Pearblossom",
  "Pismo beach",
  "Pixley",
  "Planada",
  "Porterville",
  "Posey",
  "Prather",
  "Raisin city",
  "Raymond",
  "Reedley",
  "Ridgecrest",
  "Ripon",
  "Riverbank",
  "Riverdale",
  "Rosamond",
  "Salida",
  "Salinas",
  "San joaquin",
  "San luis obispo",
  "Sanger",
  "Santa maria",
  "Selma",
  "Shafter",
  "Shaver lake",
  "Snelling",
  "Sonora",
  "Soulsbyville",
  "Springville",
  "Squaw valley",
  "Stevinson",
  "Stockton",
  "Stratford",
  "Strathmore",
  "Taft",
  "Tehachapi",
  "Terra bella",
  "Three rivers",
  "Tipton",
  "Tollhouse",
  "Tracy",
  "Tranquillity",
  "Trona",
  "Tulare",
  "Tuolumne",
  "Turlock",
  "Twain harte",
  "Valyermo",
  "Vernalis",
  "Visalia",
  "Wasco",
  "Waterford",
  "Watsonville",
  "Weldon",
  "Winton",
  "Wishon",
  "Wofford heights",
  "Woodlake",
);

    //Southern California City Names 
$southern_california = array(
  "Aliso Viejo",
  "Anaheim",
  "Atwood",
  "Azusa",
  "Baldwin Park",
  "Big Bear City",
  "Big Bear Lake",
  "Bloomington",
  "Blue Jay",
  "Brea",
  "Bryn Mawr",
  "Calimesa",
  "Capistrano Beach",
  "Cedar Glen",
  "Cedarpines Park",
  "Chino",
  "Chino Hills",
  "Claremont",
  "Colton",
  "Corona",
  "Corona Del Mar",
  "Costa Mesa",
  "Covina",
  "Crestline",
  "Dana Point",
  "Diamond Bar",
  "Duarte",
  "East Irvine",
  "El Toro",
  "Fawnskin",
  "Fontana",
  "Foothill Ranch",
  "Fountain Valley",
  "Fullerton",
  "Garden Grove",
  "Glendora",
  "Grand Terrace",
  "Green Valley Lake",
  "Guasti",
  "Hacienda Heights",
  "Hemet",
  "Highland",
  "Homeland",
  "Huntington Beach",
  "Irvine",
  "Inland Empire",
  "Jurupa Valley",
  "La Habra",
  "La Puente",
  "La Verne",
  "Ladera Ranch",
  "Laguna Beach",
  "Laguna Hills",
  "Laguna Niguel",
  "Laguna Woods",
  "Lake Arrowhead",
  "Lake Elsinore",
  "Lake Forest",
  "Loma Linda",
  "Lytle Creek",
  "Menifee",
  "Mentone",
  "Midway City",
  "Mira Loma",
  "Mission Viejo",
  "Monrovia",
  "Montclair",
  "Moreno Valley",
  "Mt Baldy",
  "Murrieta",
  "Newport Beach",
  "Newport Coast",
  "Norco",
  "Nuevo",
  "Ontario",
  "Orange",
  "Patton",
  "Perris",
  "Placentia",
  "Pomona",
  "Rancho Cucamonga",
  "Rancho Santa Margarita",
  "Redlands",
  "Rialto",
  "Rimforest",
  "Rowland Heights",
  "Running Springs",
  "San Bernardino",
  "San Clemente",
  "San Dimas",
  "San Diego County",
  "San Jacinto",
  "San Juan Capistrano",
  "Santa Ana",
  "Silverado",
  "Skyforest",
  "Southern California",
  "Temecula",
  "Temecula Valley",
  "Trabuco Canyon",
  "Tustin",
  "Twin Peaks",
  "Upland",
  "Valyermo",
  "Villa Park",
  "Walnut",
  "West Covina",
  "Westminster",
  "Wildomar",
  "Winchester",
  "Wrightwood",
  "Yorba Linda",
  "Yucaipa",
);

    //colorado
$colorado = array(

  "Aguilar",
  "Akron",
  "Alamosa",
  "Alma",
  "Antonito",
  "Arriba",
  "Arvada",
  "Aspen",
  "Ault",
  "Aurora",
  "Avon",
  "Basalt",
  "Bayfield",
  "Bennett",
  "Berthoud",
  "Bethune",
  "Black Hawk",
  "Blanca",
  "Blue River",
  "Bonanza",
  "Boone",
  "Boulder",
  "Bow Mar",
  "Branson",
  "Breckenridge",
  "Brighton",
  "Brookside",
  "Broomfield",
  "Brush",
  "Buena Vista",
  "Burlington",
  "Colorado",
  "Calhan",
  "Campo",
  "Canon City",
  "Carbondale",
  "Castle Pines",
  "Castle Rock",
  "Cedaredge",
  "Centennial",
  "Center",
  "Central City",
  "Cheraw",
  "Cherry Hills Village",
  "Cheyenne Wells",
  "Coal Creek",
  "Cokedale",
  "Collbran",
  "Colorado Springs",
  "Columbine Valley",
  "Commerce City",
  "Cortez",
  "Craig",
  "Crawford",
  "Creede",
  "Crested Butte",
  "Crestone",
  "Cripple Creek",
  "Crook",
  "Crowley",
  "Dacono",
  "De Beque",
  "Deer Trail",
  "Del Norte",
  "Delta",
  "Denver",
  "Dillon",
  "Dinosaur",
  "Dolores",
  "Dove Creek",
  "Durango",
  "Eads",
  "Eagle",
  "Eaton",
  "Eckley",
  "Edgewater",
  "Elizabeth",
  "Empire",
  "Englewood",
  "Erie",
  "Estes Park",
  "Evans",
  "Fairplay",
  "Federal Heights",
  "Firestone",
  "Flagler",
  "Fleming",
  "Florence",
  "Fort Collins",
  "Fort Lupton",
  "Fort Morgan",
  "Fountain",
  "Fowler",
  "Foxfield",
  "Fraser",
  "Frederick",
  "Frisco",
  "Fruita",
  "Garden City",
  "Genoa",
  "Georgetown",
  "Gilcrest",
  "Glendale",
  "Glenwood Springs",
  "Golden",
  "Granada",
  "Granby",
  "Grand Junction",
  "Grand Lake",
  "Greeley",
  "Green Mountain Falls",
  "Greenwood Village",
  "Grover",
  "Gunnison",
  "Gypsum",
  "Hartman",
  "Haswell",
  "Haxtun",
  "Hayden",
  "Hillrose",
  "Holly",
  "Holyoke",
  "Hooper",
  "Hot Sulphur Springs",
  "Hotchkiss",
  "Hudson",
  "Hugo",
  "Idaho Springs",
  "Ignacio",
  "Iliff",
  "Jamestown",
  "Johnstown",
  "Julesburg",
  "Keenesburg",
  "Kersey",
  "Kim",
  "Kiowa",
  "Kit Carson",
  "Kremmling",
  "La Jara",
  "La Junta",
  "La Veta",
  "Lafayette",
  "Lake City",
  "Lakeside",
  "Lakewood",
  "Lamar",
  "Larkspur",
  "Las Animas",
  "LaSalle",
  "Leadville",
  "Limon",
  "Littleton",
  "Lochbuie",
  "Log Lane Village",
  "Lone Tree",
  "Longmont",
  "Louisville",
  "Loveland",
  "Lyons",
  "Manassa",
  "Mancos",
  "Manitou Springs",
  "Manzanola",
  "Marble",
  "Mead",
  "Meeker",
  "Merino",
  "Milliken",
  "Minturn",
  "Moffat",
  "Monte Vista",
  "Montezuma",
  "Montrose",
  "Monument",
  "Morrison",
  "Mount Crested Butte",
  "Mountain View",
  "Mountain Village",
  "Naturita",
  "Nederland",
  "New Castle",
  "Northglenn",
  "Norwood",
  "Nucla",
  "Nunn",
  "Oak Creek",
  "Olathe",
  "Olney Springs",
  "Ophir",
  "Orchard City",
  "Ordway",
  "Otis",
  "Ouray",
  "Ovid",
  "Pagosa Springs",
  "Palisade",
  "Palmer Lake",
  "Paoli",
  "Paonia",
  "Parachute",
  "Parker",
  "Peetz",
  "Pierce",
  "Pitkin",
  "Platteville",
  "Poncha Springs",
  "Pritchett",
  "Pueblo",
  "Ramah",
  "Rangely",
  "Raymer",
  "Red Cliff",
  "Rico",
  "Ridgway",
  "Rifle",
  "Rockvale",
  "Rocky Ford",
  "Romeo",
  "Rye",
  "Saguache",
  "Salida",
  "San Luis",
  "Sanford",
  "Sawpit",
  "Sedgwick",
  "Seibert",
  "Severance",
  "Sheridan",
  "Sheridan Lake",
  "Silt",
  "Silver Cliff",
  "Silver Plume",
  "Silverthorne",
  "Silverton",
  "Simla",
  "Snowmass Village",
  "South Fork",
  "Springfield",
  "Starkville",
  "Steamboat Springs",
  "Sterling",
  "Stratton",
  "Sugar City",
  "Superior",
  "Swink",
  "Telluride",
  "Thornton",
  "Timnath",
  "Trinidad",
  "Two Buttes",
  "Vail",
  "Victor",
  "Vilas",
  "Vona",
  "Walden",
  "Walsenburg",
  "Walsh",
  "Ward",
  "Wellington",
  "Westcliffe",
  "Westminster",
  "Wheat Ridge",
  "Wiggins",
  "Wiley",
  "Williamsburg",
  "Windsor",
  "Winter Park",
  "Woodland Park",
  "Wray",
  "Yampa",
  "Yuma",
);

$connecticut = array(
  "Andover",
  "Ansonia",
  "Ashford",
  "Avon",
  "Barkhamsted",
  "Beacon Falls",
  "Berlin",
  "Bethany",
  "Bethel",
  "Bethlehem",
  "Bloomfield",
  "Bolton",
  "Bozrah",
  "Branford",
  "Bridgeport",
  "Bridgewater",
  "Bristol",
  "Brookfield",
  "Brooklyn",
  "Burlington",
  "Connecticut",
  "Canaan",
  "Canterbury",
  "Canton",
  "Chaplin",
  "Cheshire",
  "Chester",
  "Clinton",
  "Colchester",
  "Colebrook",
  "Columbia",
  "Cornwall",
  "Coventry",
  "Cromwell",
  "Danbury",
  "Darien",
  "Deep River",
  "Derby",
  "Durham",
  "East Granby",
  "East Haddam",
  "East Hampton",
  "East Hartford",
  "East Haven",
  "East Lyme",
  "East Windsor",
  "Eastford",
  "Easton",
  "Ellington",
  "Enfield",
  "Essex",
  "Fairfield",
  "Farmington",
  "Franklin",
  "Glastonbury",
  "Goshen",
  "Granby",
  "Greenwich",
  "Griswold",
  "Groton",
  "Guilford",
  "Haddam",
  "Hamden",
  "Hampton",
  "Hartford",
  "Hartland",
  "Harwinton",
  "Hebron",
  "Kent",
  "Killingly",
  "Killingworth",
  "Lebanon",
  "Ledyard",
  "Lisbon",
  "Litchfield",
  "Lyme",
  "Madison",
  "Manchester",
  "Mansfield",
  "Marlborough",
  "Meriden",
  "Middlebury",
  "Middlefield",
  "Middletown",
  "Milford",
  "Monroe",
  "Montville",
  "Morris",
  "Naugatuck",
  "Newington",
  "Newtown",
  "New Britain",
  "New Canaan",
  "New Fairfield",
  "New Hartford",
  "New Haven",
  "New London",
  "New Milford",
  "Norfolk",
  "North Branford",
  "North Canaan",
  "North Haven",
  "North Stonington",
  "Norwalk",
  "Norwich",
  "Old Lyme",
  "Old Saybrook",
  "Orange",
  "Oxford",
  "Plainfield",
  "Plainville",
  "Plymouth",
  "Pomfret",
  "Portland",
  "Preston",
  "Prospect",
  "Putnam",
  "Redding",
  "Ridgefield",
  "Rocky Hill",
  "Roxbury",
  "Salem",
  "Salisbury",
  "Scotland",
  "Seymour",
  "Sharon",
  "Shelton",
  "Sherman",
  "Simsbury",
  "Somers",
  "South Windsor",
  "Southbury",
  "Southington",
  "Sprague",
  "Stafford",
  "Stamford",
  "Sterling",
  "Stonington",
  "Stratford",
  "Suffield",
  "Thomaston",
  "Thompson",
  "Tolland",
  "Torrington",
  "Trumbull",
  "Union",
  "Vernon",
  "Voluntown",
  "Wallingford",
  "Warren",
  "Washington",
  "Waterbury",
  "Waterford",
  "Watertown",
  "West Hartford",
  "West Haven",
  "Westbrook",
  "Weston",
  "Westport",
  "Wethersfield",
  "Willington",
  "Wilton",
  "Winchester",
  "Windham",
  "Windsor",
  "Windsor Locks",
  "Wolcott",
  "Woodbridge",
  "Woodbury",
  "Woodstock",
);

$massachusetts = array(
  "Abington",
  "Acushnet Center",
  "Adams",
  "Agawam",
  "Amesbury",
  "Amherst Center",
  "Andover",
  "Arlington",
  "Athol",
  "Attleboro",
  "Ayer",
  "Baldwinville",
  "Barnstable Town",
  "Barre",
  "Belchertown",
  "Bellingham",
  "Belmont",
  "Beverly",
  "Bliss Corner",
  "Bondsville",
  "Boston",
  "Bourne",
  "Boxford",
  "Braintree",
  "Brewster",
  "Bridgewater",
  "Brockton",
  "Brookline",
  "Burlington",
  "Buzzards Bay",
  "Cambridge",
  "Chatham",
  "Chelsea",
  "Chicopee",
  "Clinton",
  "Cochituate",
  "Cordaville",
  "Danvers",
  "Dedham",
  "Dennis",
  "Dennis Port",
  "Dover",
  "Duxbury",
  "East Brookfield",
  "East Dennis",
  "East Douglas",
  "East Falmouth",
  "Easthampton",
  "East Harwich",
  "East Pepperell",
  "East Sandwich",
  "Essex",
  "Everett",
  "Fall River",
  "Falmouth",
  "Fiskdale",
  "Fitchburg",
  "Forestdale",
  "Fort Devens",
  "Foxborough",
  "Framingham",
  "Franklin",
  "Gardner",
  "Gloucester",
  "Granby",
  "Great Barrington",
  "Greenfield",
  "Green Harbor-Cedar Crest",
  "Groton",
  "Hanson",
  "Harwich Center",
  "Harwich Port",
  "Hatfield",
  "Haverhill",
  "Hingham",
  "Holbrook",
  "Holland",
  "Holyoke",
  "Hopedale",
  "Hopkinton",
  "Housatonic",
  "Hudson",
  "Hull",
  "Ipswich",
  "Kingston",
  "Lawrence",
  "Lee",
  "Lenox",
  "Leominster",
  "Lexington",
  "Littleton Common",
  "Longmeadow",
  "Lowell",
  "Lunenburg",
  "Lynn",
  "Lynnfield",
  "Massachusetts",
  "Malden",
  "Mansfield Center",
  "Marblehead",
  "Marion Center",
  "Marlborough",
  "Marshfield",
  "Marshfield Hills",
  "Mashpee Neck",
  "Mattapoisett Center",
  "Maynard",
  "Medfield",
  "Medford",
  "Melrose",
  "Methuen",
  "Middleborough Center",
  "Milford",
  "Millers Falls",
  "Millis-Clicquot",
  "Milton",
  "Monomoscoy Island",
  "Monson Center",
  "Monument Beach",
  "Nahant",
  "Nantucket",
  "Needham",
  "New Bedford",
  "Newburyport",
  "New Seabury",
  "Newton",
  "North Adams",
  "North Amherst",
  "Northampton",
  "North Attleborough Center",
  "Northborough",
  "North Brookfield",
  "North Eastham",
  "North Falmouth",
  "Northfield",
  "North Lakeville",
  "North Pembroke",
  "North Plymouth",
  "North Scituate",
  "North Seekonk",
  "Northwest Harwich",
  "North Westport",
  "Norton Center",
  "Norwood",
  "Ocean Bluff-Brant Rock",
  "Ocean Grove",
  "Onset",
  "Orange",
  "Orleans",
  "Oxford",
  "Palmer",
  "Peabody",
  "Pepperell",
  "Pinehurst",
  "Pittsfield",
  "Plymouth",
  "Pocasset",
  "Popponesset",
  "Popponesset Island",
  "Provincetown",
  "Quincy",
  "Randolph",
  "Raynham Center",
  "Reading",
  "Revere",
  "Rockport",
  "Rowley",
  "Rutland",
  "Sagamore",
  "Salem",
  "Salisbury",
  "Sandwich",
  "Saugus",
  "Scituate",
  "Seabrook",
  "Seconsett Island",
  "Sharon",
  "Shelburne Falls",
  "Shirley",
  "Smith Mills",
  "Somerset",
  "Somerville",
  "South Amherst",
  "South Ashburnham",
  "Southbridge",
  "South Deerfield",
  "South Dennis",
  "South Duxbury",
  "South Lancaster",
  "South Yarmouth",
  "Spencer",
  "Springfield",
  "Stoneham",
  "Sturbridge",
  "Swampscott",
  "Taunton",
  "Teaticket",
  "Three Rivers",
  "Topsfield",
  "Townsend",
  "Turners Falls",
  "Upton-West Upton",
  "Vineyard Haven",
  "Wakefield",
  "Walpole",
  "Waltham",
  "Ware",
  "Wareham Center",
  "Warren",
  "Watertown",
  "Webster",
  "Wellesley",
  "Westborough",
  "West Brookfield",
  "West Chatham",
  "West Concord",
  "West Dennis",
  "West Falmouth",
  "Westfield",
  "West Springfield",
  "West Wareham",
  "West Yarmouth",
  "Weweantic",
  "Weymouth",
  "White Island Shores",
  "Whitinsville",
  "Wilbraham",
  "Williamstown",
  "Wilmington",
  "Winchendon",
  "Winchester",
  "Winthrop",
  "Woburn",
  "Woods Hole",
  "Worcester",
  "Yarmouth Port",
);

$new_jersey = array(
  "Absecon",
  "Allamuchy-Panther Valley",
  "Allendale",
  "Allenhurst",
  "Allentown",
  "Allenwood",
  "Alloway",
  "Alpha",
  "Alpine",
  "Andover",
  "Annandale",
  "Asbury Park",
  "Ashland",
  "Atlantic City",
  "Atlantic Highlands",
  "Audubon",
  "Audubon Park",
  "Avalon",
  "Avenel",
  "Avon-by-the-Sea",
  "Barclay-Kingston",
  "Barnegat",
  "Barnegat Light",
  "Barrington",
  "Bay Head",
  "Bayonne",
  "Beach Haven",
  "Beach Haven West",
  "Beachwood",
  "Beatyestown",
  "Beckett",
  "Belford",
  "Belleville",
  "Bellmawr",
  "Belmar",
  "Belvidere",
  "Bergenfield",
  "Berkeley Heights",
  "Berlin",
  "Bernardsville",
  "Beverly",
  "Blackwood",
  "Bloomfield",
  "Bloomingdale",
  "Bloomsbury",
  "Bogota",
  "Boonton",
  "Bordentown",
  "Bound Brook",
  "Bradley Beach",
  "Branchville",
  "Brass Castle",
  "Bridgeton",
  "Brielle",
  "Brigantine",
  "Brooklawn",
  "Browns Mills",
  "Brownville",
  "Budd Lake",
  "Buena",
  "Burlington",
  "Butler",
  "Caldwell",
  "Califon",
  "Camden",
  "Cape May",
  "Cape May Court House",
  "Cape May Point",
  "Carlstadt",
  "Carneys Point",
  "Carteret",
  "Cedar Glen Lakes",
  "Cedar Glen West",
  "Cedar Grove",
  "Cedarville",
  "Chatham",
  "Cherry Hill Mall",
  "Chesilhurst",
  "Chester",
  "Clark",
  "Clayton",
  "Clearbrook Park",
  "Clementon",
  "Cliffside Park",
  "Cliffwood Beach",
  "Clifton",
  "Clinton",
  "Closter",
  "Collings Lakes",
  "Collingswood",
  "Colonia",
  "Concordia",
  "Corbin City",
  "Country Lake Estates",
  "Cranbury",
  "Crandon Lakes",
  "Cranford",
  "Cresskill",
  "Crestwood Village",
  "Dayton",
  "Deal",
  "Demarest",
  "Diamond Beach",
  "Dover",
  "Dover Beaches North",
  "Dover Beaches South",
  "Dumont",
  "Dunellen",
  "East Brunswick",
  "East Freehold",
  "East Newark",
  "East Orange",
  "East Rutherford",
  "Eatontown",
  "Echelon",
  "Edgewater",
  "Edison",
  "Egg Harbor City",
  "Elizabeth",
  "Elmer",
  "Elmwood Park",
  "Elwood-Magnolia",
  "Emerson",
  "Englewood",
  "Englewood Cliffs",
  "Englishtown",
  "Erlton-Ellisburg",
  "Erma",
  "Essex Fells",
  "Estell Manor",
  "Ewing",
  "Fairfield",
  "Fair Haven",
  "Fair Lawn",
  "Fairton",
  "Fairview",
  "Fairview",
  "Fanwood",
  "Far Hills",
  "Farmingdale",
  "Fieldsboro",
  "Flemington",
  "Florence-Roebling",
  "Florham Park",
  "Folsom",
  "Fords",
  "Forked River",
  "Fort Dix",
  "Fort Lee",
  "Franklin",
  "Franklin Lakes",
  "Freehold",
  "Frenchtown",
  "Garfield",
  "Garwood",
  "Gibbsboro",
  "Gibbstown",
  "Glassboro",
  "Glendora",
  "Glen Gardner",
  "Glen Ridge",
  "Glen Rock",
  "Gloucester City",
  "Golden Triangle",
  "Great Meadows-Vienna",
  "Greentree",
  "Guttenberg",
  "Hackensack",
  "Hackettstown",
  "Haddonfield",
  "Haddon Heights",
  "Haledon",
  "Hamburg",
  "Hammonton",
  "Hampton",
  "Harrington Park",
  "Harrison",
  "Harvey Cedars",
  "Hasbrouck Heights",
  "Haworth",
  "Hawthorne",
  "Heathcote",
  "Helmetta",
  "High Bridge",
  "Highland Lake",
  "Highland Park",
  "Highlands",
  "Hightstown",
  "Hillsdale",
  "Hillside",
  "Hi-Nella",
  "Hoboken",
  "Ho-Ho-Kus",
  "Holiday City-Berkeley",
  "Holiday City South",
  "Holiday Heights",
  "Hopatcong",
  "Hopewell",
  "Interlaken",
  "Irvington",
  "Iselin",
  "Island Heights",
  "Jamesburg",
  "Jersey City",
  "Keansburg",
  "Kearny",
  "Kendall Park",
  "Kenilworth",
  "Keyport",
  "Kingston",
  "Kinnelon",
  "Lakehurst",
  "Lake Mohawk",
  "Lake Telemark",
  "Lakewood",
  "Lambertville",
  "Laurel Lake",
  "Laurel Springs",
  "Laurence Harbor",
  "Lavallette",
  "Lawnside",
  "Lawrenceville",
  "Lebanon",
  "Leisure Knoll",
  "Leisuretowne",
  "Leisure Village",
  "Leisure Village East",
  "Leisure Village West-Pine Lake Park",
  "Leonardo",
  "Leonia",
  "Lincoln Park",
  "Lincroft",
  "Linden",
  "Lindenwold",
  "Linwood",
  "Little Falls",
  "Little Ferry",
  "Little Silver",
  "Livingston",
  "Loch Arbour village",
  "Lodi",
  "Long Branch",
  "Longport",
  "Long Valley",
  "Lyndhurst",
  "McGuire AFB",
  "Madison",
  "Madison Park",
  "Magnolia",
  "Manahawkin",
  "Manasquan",
  "Mantoloking",
  "Manville",
  "Maplewood",
  "Margate City",
  "Marlton",
  "Matawan",
  "Mays Landing",
  "Maywood",
  "Medford Lakes",
  "Mendham",
  "Mercerville-Hamilton Square",
  "Merchantville",
  "Metuchen",
  "Middlesex",
  "Midland Park",
  "Milford",
  "Millburn",
  "Millstone",
  "Milltown",
  "Millville",
  "Monmouth Beach",
  "Monmouth Junction",
  "Montclair",
  "Montvale",
  "Moonachie",
  "Moorestown-Lenola",
  "Morganville",
  "Morris Plains",
  "Morristown",
  "Mountain Lakes",
  "Mountainside",
  "Mount Arlington",
  "Mount Ephraim",
  "Mullica Hill",
  "Mystic Island",
  "National Park",
  "Navesink",
  "Neptune City",
  "Netcong",
  "Newark",
  "New Brunswick",
  "New Egypt",
  "New Jersey",
  "Newfield",
  "New Milford",
  "New Providence",
  "Newton",
  "North Arlington",
  "North Beach Haven",
  "North Brunswick Township",
  "North Caldwell",
  "North Cape May",
  "Northfield",
  "North Haledon",
  "North Middletown",
  "North Plainfield",
  "Northvale",
  "North Wildwood",
  "Norwood",
  "Nutley",
  "Oakhurst",
  "Oakland",
  "Oaklyn",
  "Oak Valley",
  "Ocean Acres",
  "Ocean City",
  "Ocean Gate",
  "Ocean Grove",
  "Oceanport",
  "Ogdensburg",
  "Old Bridge",
  "Old Tappan",
  "Olivet",
  "Oradell",
  "Orange",
  "Oxford",
  "Palisades Park",
  "Palmyra",
  "Paramus",
  "Park Ridge",
  "Passaic",
  "Paterson",
  "Paulsboro",
  "Peapack and Gladstone",
  "Pemberton",
  "Pemberton Heights",
  "Pennington",
  "Pennsauken",
  "Penns Grove",
  "Pennsville",
  "Perth Amboy",
  "Phillipsburg",
  "Pine Beach",
  "Pine Hill",
  "Pine Ridge at Crestwood",
  "Pine Valley",
  "Pitman",
  "Plainfield",
  "Plainsboro Center",
  "Pleasantville",
  "Point Pleasant",
  "Point Pleasant Beach",
  "Pomona",
  "Pompton Lakes",
  "Port Monmouth",
  "Port Norris",
  "Port Reading",
  "Port Republic",
  "Presidential Lakes Estates",
  "Princeton",
  "Princeton Junction",
  "Princeton Meadows",
  "Princeton North",
  "Prospect Park",
  "Rahway",
  "Ramblewood",
  "Ramsey",
  "Ramtown",
  "Raritan",
  "Red Bank",
  "Ridgefield",
  "Ridgefield Park village",
  "Ridgewood village",
  "Ringwood",
  "Rio Grande",
  "Riverdale",
  "River Edge",
  "Riverton",
  "River Vale",
  "Rochelle Park",
  "Rockaway",
  "Rockleigh",
  "Rocky Hill",
  "Roosevelt",
  "Roseland",
  "Roselle",
  "Roselle Park",
  "Rosenhayn",
  "Rossmoor",
  "Rumson",
  "Runnemede",
  "Rutherford",
  "Saddle Brook",
  "Saddle River",
  "Salem",
  "Sayreville",
  "Scotch Plains",
  "Sea Bright",
  "Seabrook Farms",
  "Sea Girt",
  "Sea Isle City",
  "Seaside Heights",
  "Seaside Park",
  "Secaucus",
  "Sewaren",
  "Shark River Hills",
  "Shiloh",
  "Ship Bottom",
  "Shrewsbury",
  "Silver Ridge",
  "Society Hill",
  "Somerdale",
  "Somerset",
  "Somers Point",
  "Somerville",
  "South Amboy",
  "South Belmar",
  "South Bound Brook",
  "South Orange",
  "South Plainfield",
  "South River",
  "South Toms River",
  "Spotswood",
  "Springdale",
  "Springfield",
  "Spring Lake",
  "Spring Lake Heights",
  "Stanhope",
  "Stockton",
  "Stone Harbor",
  "Stratford",
  "Strathmere",
  "Strathmore",
  "Succasunna-Kenvil",
  "Summit",
  "Surf City",
  "Sussex",
  "Swedesboro",
  "Tavistock",
  "Teaneck",
  "Tenafly",
  "Teterboro",
  "Tinton Falls",
  "Toms River",
  "Totowa",
  "Trenton",
  "Tuckerton",
  "Turnersville",
  "Twin Rivers",
  "Union",
  "Union Beach",
  "Union City",
  "Upper Saddle River",
  "Ventnor City",
  "Vernon Valley",
  "Verona",
  "Victory Gardens",
  "Victory Lakes",
  "Villas",
  "Vineland",
  "Vista Center",
  "Waldwick",
  "Wallington",
  "Wanamassa",
  "Wanaque",
  "Waretown",
  "Washington",
  "Washington Township",
  "Watchung",
  "Wayne",
  "Wenonah",
  "West Belmar",
  "West Caldwell",
  "West Cape May",
  "Westfield",
  "West Freehold",
  "West Long Branch",
  "West Milford",
  "West New York",
  "West Orange",
  "West Paterson",
  "Westville",
  "West Wildwood",
  "Westwood",
  "Wharton",
  "White Horse",
  "White House Station",
  "White Meadow Lake",
  "Whitesboro-Burleigh",
  "Whittingham",
  "Wildwood",
  "Wildwood Crest",
  "Williamstown",
  "Woodbine",
  "Woodbridge",
  "Woodbury",
  "Woodbury Heights",
  "Woodcliff Lake",
  "Woodlynne",
  "Wood-Ridge",
  "Woodstown",
  "Wrightstown",
  "Wyckoff",
  "Yardville-Groveville",
  "Yorketown",
);

$test_city = array(
  //belongs in southern california
  "Beaumont",
);

?>

<?php if (in_array(get_field('city_name'), $northern_california)) : ?>

  <div>
    <?php echo get_template_part('partials/city-pages/north-california2'); ?>

  </div>

  <?php elseif (in_array(get_field('city_name'), $central_california)) : ?>

    <div>
      <?php echo get_template_part('partials/city-pages/central-california2'); ?>

    </div>

    <?php elseif (in_array(get_field('city_name'), $test_city)) : ?>

      <?php echo ""; ?>


      <?php elseif (in_array(get_field('city_name'), $southern_california)) : ?>

        <div>
          <?php echo get_template_part('partials/city-pages/southern-california2'); ?>
        </div>

        <?php elseif (in_array(get_field('city_name'), $colorado)) : ?>

          <div>
            <?php echo get_template_part('partials/city-pages/colorado'); ?>
          </div>

          <?php elseif (in_array(get_field('city_name'), $connecticut)) : ?>

            <div>
              <?php echo get_template_part('partials/city-pages/connecticut'); ?>
            </div>

            <?php elseif (in_array(get_field('city_name'), $massachusetts)) : ?>

              <div>
                <?php echo get_template_part('partials/city-pages/massachusetts'); ?>
              </div>

              <?php elseif (in_array(get_field('city_name'), $new_jersey)) : ?>

                <div>
                  <?php echo get_template_part('partials/city-pages/new-jersey'); ?>
                </div>



                <?php else : ?>

                  <div>
                    <?php echo get_template_part('partials/city-pages/north-california2'); ?>

                  </div>
                  <div>
                    <?php echo get_template_part('partials/city-pages/central-california2'); ?>

                  </div>

                  <div>
                    <?php echo get_template_part('partials/city-pages/southern-california2'); ?>
                  </div>

                <?php endif; ?>




              </main><!--end main-->

              <!-- mobile Modal -->
              <?php echo get_template_part('partials/forms/mobileModal'); ?>

              <!-- Full Screen Modal -->
              <?php echo get_template_part('partials/forms/fullscreenModal'); ?>
            </div>
            <?php echo get_template_part('partials/footer'); ?>